version: "3"
services:
  jenkins:
    container_name: jenkins
    user: 1000:999
    image: "jenkins/jenkins:lts-alpine"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
